import sys, os; sys.stdout.reconfigure(encoding='utf-8')
from sw import api, write; from sw.models import DocSelector; from sw.selectors import resolve
D = r'<CAD_DIR>'
TPL = r'c:\solidworks data\00. <USER> 솔리드웍스 템플릿\01. 문서 템플릿\이텍 Part.prtdot'
MAT = r'c:\solidworks data\00. retech 솔리드웍스 템플릿\05. 재질 데이터베이스\이텍.sldmat'
app = api.get_app()
def new_part(): return api.cast('IModelDoc2', api.dyn(app).NewDocument(TPL, 0, 0, 0))
def finish(m, path, mass_expect):
    pd = api.cast('IPartDoc', m); ext = api.cast('IModelDocExtension', m.Extension)
    pd.SetMaterialPropertyName2('', MAT, 'STS 304'); m.ForceRebuild3(False)
    print('  box', [round(v*1000,1) for v in pd.GetPartBox(True)], '| 오류', ext.GetWhatsWrongCount())
    print('  mass %.3f kg' % api.cast('IMassProperty', ext.CreateMassProperty()).Mass)
    r = write.save_model(app, m, out_path=path); print('  saved', r['errors'], os.path.basename(path))
# 1) S30007 충전구 커브: 450/459 정사각 링 x 25H
m = new_part(); api.activate(app, m)
ext = api.cast('IModelDocExtension', m.Extension); skm = api.cast('ISketchManager', m.SketchManager)
ok = ext.SelectByID2('윗면', 'PLANE', 0,0,0, False, 0, None, 0)
if not ok: ok = ext.SelectByID2('Top Plane', 'PLANE', 0,0,0, False, 0, None, 0)
print('S30007 plane sel', ok)
skm.InsertSketch(True)
skm.CreateCornerRectangle(-0.2295, -0.2295, 0, 0.2295, 0.2295, 0)
skm.CreateCornerRectangle(-0.225, -0.225, 0, 0.225, 0.225, 0)
skm.InsertSketch(True)
fm = api.cast('IFeatureManager', m.FeatureManager)
m.ClearSelection2(True); ext.SelectByID2('스케치1', 'SKETCH', 0,0,0, False, 0, None, 0)
f = fm.FeatureExtrusion3(True, False, False, 0, 0, 0.025, 0.0, False, False, False, False, 0.0, 0.0, False, False, False, False, True, True, True, 0, 0.0, False)
print('  extrude', f is not None)
finish(m, os.path.join(D, 'S30007MU0.SLDPRT'), 1.8)
# 2) S30009 용접 힌지 배럴: Ø16 x 60 (축 = X)
m = new_part(); api.activate(app, m)
ext = api.cast('IModelDocExtension', m.Extension); skm = api.cast('ISketchManager', m.SketchManager)
ok = ext.SelectByID2('우측면', 'PLANE', 0,0,0, False, 0, None, 0)
if not ok: ok = ext.SelectByID2('Right Plane', 'PLANE', 0,0,0, False, 0, None, 0)
print('S30009 plane sel', ok)
skm.InsertSketch(True)
skm.CreateCircleByRadius(0, 0, 0, 0.008)
skm.InsertSketch(True)
fm = api.cast('IFeatureManager', m.FeatureManager)
m.ClearSelection2(True); ext.SelectByID2('스케치1', 'SKETCH', 0,0,0, False, 0, None, 0)
f = fm.FeatureExtrusion3(True, False, False, 0, 0, 0.060, 0.0, False, False, False, False, 0.0, 0.0, False, False, False, False, True, True, True, 0, 0.0, False)
print('  extrude', f is not None)
finish(m, os.path.join(D, 'S30009MU0.SLDPRT'), 0.09)
